name: Release

on:
  release:
    types: [published]  

permissions:
  contents: write
  packages: write

jobs:
  version:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    outputs:
      version: ${{ steps.get-tag-version.outputs.version }}

    steps:
      - name: Get Tag Version
        id: get-tag-version
        shell: bash
        run: |
          tagName="${{ github.event.release.tag_name }}"
          version="${tagName#v}"  # Removes the 'v' prefix if it exists
          echo "Extracted version $version from tag"
          echo "version=$version" >> "$GITHUB_OUTPUT"

  publish:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: [version]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch twine build

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with setup.py using version
        run: |
          hatch build

      - name: Publish to NCL on Pypi
        env:
          TWINE_REPOSITORY_URL: https://pypi.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: twine upload --verbose dist/*